version: 3.00.00.{build}

os: Visual Studio 2017

branches:
  except:
    - configdata
    - gh-pages

environment:
  matrix:
  - IdeVersion: VS2017
  SKIP_PAUSE: TRUE
  ARCHIVE_WITH_PDB: TRUE
  spciuser: ""

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  # enable MSBuild parallel builds
  parallel: true
  # MSBuild verbosity level
  verbosity: minimal

cache:
  #- packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages\WiX.3.11.0 -> Setup\packages.config

install:
- cmd: git submodule update --init --recursive
- cmd: echo /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll">> Directory.Build.rsp
- cmd: |-
    cd Setup
    python set_version_to.py -v %APPVEYOR_BUILD_VERSION% -t %APPVEYOR_BUILD_VERSION%
    cd ..

# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: |
    Write-Output "Platform: $env:IdeVersion"
    # for release branches mark the repo as clean
    if (!$env:APPVEYOR_PULL_REQUEST_TITLE -and $env:APPVEYOR_REPO_BRANCH.StartsWith("release/")) {
        & git update-index --skip-worktree CommonAssemblyInfo.cs
        & git update-index --skip-worktree CommonAssemblyInfoExternals.cs
        & git update-index --skip-worktree GitExtSshAskPass/SshAskPass.rc2
        & git update-index --skip-worktree GitExtensionsShellEx/GitExtensionsShellEx.rc
        & git update-index --skip-worktree GitExtensionsVSIX/source.extension.vsixmanifest
        & git update-index --skip-worktree Setup/MakeInstallers.cmd
        & cd GitExtensionsDoc
        & git update-index --skip-worktree source/conf.py
        & cd ..\
        & git status
        & git submodule foreach --recursive git status
    }
    # build
    & Setup\Build.cmd
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

# to run your custom scripts instead of automatic tests
test_script:
- ps: Exit-AppVeyorBuild |
    $testAssemblies = (Get-ChildItem -Path UnitTests\*\bin\Release\ -Filter '*Tests.dll' -Recurse -Exclude 'ApprovalTests.dll').FullName
    $packageConfig = [xml](Get-Content .nuget\packages.config)
    $opencover_version = $packageConfig.SelectSingleNode('/packages/package[@id="OpenCover"]').version
    $opencover_console = "packages\OpenCover.$opencover_version\tools\OpenCover.Console.exe"
    &$opencover_console `
        -register:user `
        -returntargetcode `
        -hideskipped:All `
        -filter:"+[*]* -[FluentAssertions*]* -[SmartFormat*]* -[nunit*]*" `
        -excludebyattribute:*.ExcludeFromCodeCoverage* `
        -excludebyfile:*\*Designer.cs `
        -output:"OpenCover.GitExtensions.xml" `
        -target:"nunit3-console.exe" `
        -targetargs:"$testAssemblies"
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    $codecov_version = $packageConfig.SelectSingleNode('/packages/package[@id="Codecov"]').version
    $codecov = "packages\Codecov.$codecov_version\tools\codecov.exe"
    &$codecov -f ".\OpenCover.GitExtensions.xml"


# here we are going to override common configuration
for:

# configuration for all branches except release/*
-
  branches:
    except:
      - /release\/.*/

  # scripts to run after tests
  after_test:
  - ps: |
      & Setup\BuildInstallers.cmd
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      & Setup\Set-Portable.ps1
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      & Setup\MakePortableArchive.cmd Release $env:APPVEYOR_BUILD_VERSION
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

  artifacts:
    # upload the generated portable archive only
    - path: 'Setup/GitExtensions-Portable-*.zip'

# configuration for release branches ONLY
-
  branches:
    only:
      - /release\/.*/

  environment:
    spciuser:
      secure: d/ak/yIuPjpVeWl+gDR0Yl1s8L4AGP+sn46jqGl7EvVZMq0bhzZBFwBCm9JTy0P9

  # scripts to run after tests
  after_test:
  - ps: |
      # -------------------------------
      # build artifacts
      # -------------------------------
      & Setup\BuildInstallers.cmd
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      & Setup\Set-Portable.ps1 -IsPortable
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      & Setup\MakePortableArchive.cmd Release $env:APPVEYOR_BUILD_VERSION
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      & Setup\Set-Portable.ps1
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
      # -------------------------------
      # sign artifacts
      # -------------------------------
      # do sign artifacts for non-release branches
      if ($env:APPVEYOR_PULL_REQUEST_TITLE -or !$env:APPVEYOR_REPO_BRANCH.StartsWith("release/")) {
          Write-Host "[INFO]: Do not sign non-release branches"
          Get-ChildItem .\Setup\GitExtensions-Portable-*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
          Exit-AppVeyorBuild
          
          e
      }
      # continue on with signing
      pushd .\Setup
      # get files
      $msi = (Resolve-Path GitExtensions-*.msi)[0].Path;
      $zip = (Resolve-Path GitExtensions-Portable-*.zip)[0].Path;
      # archive files so we send them all in one go
      $combined = ".\combined.$($env:APPVEYOR_BUILD_VERSION).zip"
      $combinedSigned = ".\combined.$($env:APPVEYOR_BUILD_VERSION).signed.zip"
      Compress-Archive -LiteralPath $msi, $zip -CompressionLevel NoCompression -DestinationPath $combined -Force

  artifacts:
    # upload the generated portable archive only
    - path: 'Setup/combined.*.zip'

  deploy:
  - provider: Webhook
    url: https://fqa.test.signpath.io/API/v1/72ca56cc-b008-4fe1-b09c-a488981328fc/Integrations/AppVeyor?SigningPolicyId=e46710f2-2318-496c-ac5c-5d50a2b4b0f9
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false
    method: POST
    authorization:
      secure: OPxfn9gj5/uR6gufY3dRK2T/RkvkXuEhlmbNPfwdbFJl6W/jepI2Y7psbpge+dJsUR9KPjx1ZuY9lfnyiEFNhg==
